export const ADD_QUERY = 'ADD_QUERY'
export const GET_EMOTION = 'GET_EMOTION'
export const ADD_MAIN_EMOTION = 'ADD_MAIN_EMOTION'
export const ADD_SUB_EMOTION = 'ADD_SUB_EMOTION'
export const LOADING = 'LOADING'